In [1]:
print("Aaradhya Tandel , UIN :- 231A053")

Aaradhya Tandel , UIN :- 231A053

In [ ]:
Documents = [
    "Natural language processing is a fascinating field of artificial intelligence.",
    "Machine learning models require large amounts of data to train effectively.",
    "Text classification and sentiment analysis are common natural language tasks.",
    "Deep learning algorithms power modern translation and speech recognition systems.",
    "Data preprocessing is an essential step before training any machine learning model."

]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

In [ ]:
for i, doc in enumerate(Documents):
  print(f"D{i+1}: {doc}")

D1: Natural language processing is a fascinating field of artificial intelligence.
D2: Machine learning models require large amounts of data to train effectively.
D3: Text classification and sentiment analysis are common natural language tasks.
D4: Deep learning algorithms power modern translation and speech recognition systems.
D5: Data preprocessing is an essential step before training any machine learning model.

In [ ]:
vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = vectorizer.fit_transform(Documents)
print(tfidf_matrix.shape)

(5, 35)

In [ ]:
print(tfidf_matrix[0:])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 41 stored elements and shape (5, 35)>
  Coords	Values
  (0, 20)	0.32138757599667
  (0, 13)	0.32138757599667
  (0, 23)	0.3983516165374428
  (0, 10)	0.3983516165374428
  (0, 11)	0.3983516165374428
  (0, 3)	0.3983516165374428
  (0, 12)	0.3983516165374428
  (1, 16)	0.28980238712497836
  (1, 15)	0.24056216023459348
  (1, 18)	0.3592025890535391
  (1, 25)	0.3592025890535391
  (1, 14)	0.3592025890535391
  (1, 1)	0.3592025890535391
  (1, 6)	0.28980238712497836
  (1, 32)	0.3592025890535391
  (1, 8)	0.3592025890535391
  (2, 20)	0.29857028119389706
  (2, 13)	0.29857028119389706
  (2, 31)	0.3700701677555205
  (2, 4)	0.3700701677555205
  (2, 26)	0.3700701677555205
  (2, 2)	0.3700701677555205
  (2, 5)	0.3700701677555205
  (2, 30)	0.3700701677555205
  (3, 15)	0.2304080775904384
  (3, 7)	0.34404071666393615
  (3, 0)	0.34404071666393615
  (3, 21)	0.34404071666393615
  (3, 19)	0.34404071666393615
  (3, 34)	0.34404071666393615
  (3, 27)	0.34404071666393615
  (3, 24)	0.34404071666393615
  (3, 29)	0.34404071666393615
  (4, 16)	0.310527085882465
  (4, 15)	0.2577655323419535
  (4, 6)	0.310527085882465
  (4, 22)	0.3848903189749406
  (4, 9)	0.3848903189749406
  (4, 28)	0.3848903189749406
  (4, 33)	0.3848903189749406
  (4, 17)	0.3848903189749406

In [ ]:
print(vectorizer.get_feature_names_out())

['algorithms' 'amounts' 'analysis' 'artificial' 'classification' 'common'
 'data' 'deep' 'effectively' 'essential' 'fascinating' 'field'
 'intelligence' 'language' 'large' 'learning' 'machine' 'model' 'models'
 'modern' 'natural' 'power' 'preprocessing' 'processing' 'recognition'
 'require' 'sentiment' 'speech' 'step' 'systems' 'tasks' 'text' 'train'
 'training' 'translation']

In [ ]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out(),
    index=['D1', 'D2', 'D3', 'D4', 'D5']
)
tfidf_df.round(3)

,algorithms,amounts,analysis,artificial,classification,common,data,deep,effectively,essential,...,require,sentiment,speech,step,systems,tasks,text,train,training,translation
D1,0.000,0.000,0.00,0.398,0.00,0.00,0.000,0.000,0.000,0.000,...,0.000,0.00,0.000,0.000,0.000,0.00,0.00,0.000,0.000,0.000
D2,0.000,0.359,0.00,0.000,0.00,0.00,0.290,0.000,0.359,0.000,...,0.359,0.00,0.000,0.000,0.000,0.00,0.00,0.359,0.000,0.000
D3,0.000,0.000,0.37,0.000,0.37,0.37,0.000,0.000,0.000,0.000,...,0.000,0.37,0.000,0.000,0.000,0.37,0.37,0.000,0.000,0.000
D4,0.344,0.000,0.00,0.000,0.00,0.00,0.000,0.344,0.000,0.000,...,0.000,0.00,0.344,0.000,0.344,0.00,0.00,0.000,0.000,0.344
D5,0.000,0.000,0.00,0.000,0.00,0.00,0.311,0.000,0.000,0.385,...,0.000,0.00,0.000,0.385,0.000,0.00,0.00,0.000,0.385,0.000

In [ ]:
similarity_matrix = cosine_similarity(tfidf_matrix)
similarity_matrix

array([[1.        , 0.        , 0.19191356, 0.        , 0.        ],
       [0.        , 1.        , 0.        , 0.05542746, 0.24199161],
       [0.19191356, 0.        , 1.        , 0.        , 0.        ],
       [0.        , 0.05542746, 0.        , 1.        , 0.05939126],
       [0.        , 0.24199161, 0.        , 0.05939126, 1.        ]])

In [ ]:
similarity_df = pd.DataFrame(similarity_matrix, columns=['D1', 'D2', 'D3', 'D4', 'D5'], index=['D1', 'D2', 'D3', 'D4', 'D5'])
similarity_df.round(3)

       D1     D2     D3     D4     D5
D1  1.000  0.000  0.192  0.000  0.000
D2  0.000  1.000  0.000  0.055  0.242
D3  0.192  0.000  1.000  0.000  0.000
D4  0.000  0.055  0.000  1.000  0.059
D5  0.000  0.242  0.000  0.059  1.000

In [ ]:
doc2 = 1
doc4 = 5

similarity = similarity_matrix[doc1-1, doc2-1]
print(f"Similarity between D{doc1} and D{doc2}: {similarity:.3f}:")

Similarity between D3 and D1: 0.192:

In [ ]:
highest_similarity = -1
most_similar_doc = None

for i in range(len(Documents)):
  for j in range(i+1, len(Documents)):
    similarity = similarity_matrix[i][ j]
    if similarity > highest_similarity:
      highest_similarity = similarity
      most_similar_doc = (i, j)

print(
    f"The most similar documents are D{most_similar_doc[0]+1} and D{most_similar_doc[1]+1} with a similarity of {highest_similarity:.3f}"
)

The most similar documents are D2 and D5 with a similarity of 0.242

In [ ]:
def similar(D1,D2):
  vector = vectorizer.transform([D1, D2])
  similarity = cosine_similarity(vector)
  return similarity

In [ ]:
similar(Documents[0], Documents[1])

array([[1., 0.],
       [0., 1.]])